name: "Label PR"
description: "This will apply label to every open PR with needs-review"

on:
  pull_request:
    types: [opened]

jobs:
  hello:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          gh-token: ${{secrets.GITHUB_TOKEN}}
          label: 'needs-review'